### PR TITLE
Adds 2 more libraries/fixes

### PR DESCRIPTION
**Pull request by khalidahmedshalabi**
- Fix tickcount functions.
- Fix extra tildes crash issue.

### CODE REVIEW

**Comment by Gammix** [comment]
There is no need for gametext fix because they are completely based on textdraws with fix_gametext, and textdraws have feature to prevent errors like that.

**Comment by khalidahmedshalabi** [comment]
Well, what if I were to exclude your fix_gametext library but use other libraries? I think I'd need that tildes crash fix then, wouldn't I? @Gammix

**Comment by KHKKhalid** [comment]
Added 2 more commits.

**Comment by KHKKhalid** [comment]
Added more commits and updated my fork.

**Comment by khalidahmedshalabi** [comment]
d00eec45eda8a6240397cb0e5411742581dcfca0
9ad31c0548121c745f44ddad13cd52be40bbfbe7

**Pull request closed without merging**
